// 1. Define Users first
const users: any[] = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'Admin User',
    email: 'admin@coop.org',
    password: '123456',
  },
];

// 2. Define Memberships SECOND (so loanApplications can see them)
const memberships: any[] = [
  {
    id: 'd6e15727-9fe1-4961-8c5b-ea44a9bd81aa',
    title: 'Mr',
    surname: 'Okoro',
    firstName: 'Emmanuel',
    middleName: 'Chinedu',
    dateOfBirth: '1985-06-12',
    gender: 'Male',
    nationality: 'Nigerian',
    residentialAddress: '12 Market Road, Suleja',
    tin: 'TIN12345',
    email: 'emmanuel.okoro@example.com',
    mobilePhone: '08012345678',
  },
  {
    id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    title: 'Mrs',
    surname: 'Adebayo',
    firstName: 'Grace',
    middleName: null,
    dateOfBirth: '1990-03-20',
    gender: 'Female',
    nationality: 'Nigerian',
    residentialAddress: '45 Cooperative Street, Suleja',
    tin: null,
    email: 'grace.adebayo@example.com',
    mobilePhone: '08087654321',
  },
];

// 3. Define Loan Applications LAST
const loanApplications: any[] = [
  {
    id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    memberId: memberships[0].id, // Now it can find memberships!
    title: 'Mr',
    surname: 'Okoro',
    firstName: 'Emmanuel',
    middleName: 'Chinedu',
    dateOfBirth: '1985-06-12',
    gender: 'Male',
    nationality: 'Nigerian',
    residentialAddress: '12 Market Road, Suleja',
    contactAddress: 'PO Box 123, Suleja',
    tin: 'TIN12345',
    email: 'emmanuel.okoro@example.com',
    mobilePhone: '08012345678',
    loanAmount: 500000,
    requestDate: '2026-02-25',
    purposeOfLoan: 'Business Expansion',
    duration: '12 months',
    interest: '10%',
    repaymentDate: '2027-02-25',
    bankName: 'First Bank',
    accountNumber: '1234567890',
    accountName: 'Emmanuel Okoro',
    accountType: 'Savings',
    spouseName: 'Ngozi Okoro',
    spouseMobilePhone: '08023456789',
    spouseTitle: 'Mrs',
    spouseDOB: '1987-09-15',
    spouseGender: 'Female',
    spouseNationality: 'Nigerian',
    spouseStateOfOrigin: 'Delta',
    spouseLocalGovt: 'Oshimili South',
    spouseMaritalStatus: 'Married',
    spouseResidentialAddress: '12 Market Road, Suleja',
  },
  {
    id: 'CC27C14A-0ACF-4F4A-A6C9-D45682C144B9',
    memberId: memberships[1].id,
    title: 'Mrs',
    surname: 'Adebayo',
    firstName: 'Grace',
    middleName: null,
    dateOfBirth: '1990-03-20',
    gender: 'Female',
    nationality: 'Nigerian',
    residentialAddress: '45 Cooperative Street, Suleja',
    contactAddress: null,
    tin: null,
    email: 'grace.adebayo@example.com',
    mobilePhone: '08087654321',
    loanAmount: 300000,
    requestDate: '2026-02-25',
    purposeOfLoan: 'Personal Emergency',
    duration: '6 months',
    interest: '8%',
    repaymentDate: '2026-08-25',
    bankName: 'UBA',
    accountNumber: '9876543210',
    accountName: 'Grace Adebayo',
    accountType: 'Current',
    spouseName: 'Samuel Adebayo',
    spouseMobilePhone: '08076543210',
    spouseTitle: 'Mr',
    spouseDOB: '1988-11-02',
    spouseGender: 'Male',
    spouseNationality: 'Nigerian',
    spouseStateOfOrigin: 'Kwara',
    spouseLocalGovt: 'Ilorin West',
    spouseMaritalStatus: 'Married',
    spouseResidentialAddress: '45 Cooperative Street, Suleja',
  },
];

export { users, memberships, loanApplications };